version: '3.8'

services:
  web:
    build: .
    command: gunicorn edusphere.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 # Remember to turn this off in production

volumes:
  static_volume:
  media_volume:
