# Generated by Django 5.0a1 on 2023-10-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('college_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('established_year', models.IntegerField()),
                ('website', models.URLField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone_number', models.CharField(max_length=15)),
                ('college_type', models.IntegerField(choices=[(1, 'Community colleges'), (2, 'Technical colleges'), (3, 'Vocational colleges'), (4, 'Public universities'), (5, 'Private universities'), (6, 'For-profit colleges'), (7, 'Liberal arts colleges'), (8, 'Art colleges'), (9, 'Nursing schools'), (10, 'Special interest colleges')])),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='college_profile_photos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='college_cover_photos/')),
                ('verification', models.CharField(default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('pdf_copy', models.FileField(blank=True, null=True, upload_to='college_pdf_copies/')),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='cover_photos/')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
