# Generated by Django 4.2.5 on 2023-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
