# Generated by Django 5.0a1 on 2023-10-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_remove_collegeuser_established_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeuser',
            name='college_type',
            field=models.IntegerField(choices=[(1, 'Community colleges'), (2, 'Technical colleges'), (3, 'Vocational colleges'), (4, 'Public universities'), (5, 'Private universities'), (6, 'For-profit colleges'), (7, 'Liberal arts colleges'), (8, 'Art colleges'), (9, 'Nursing schools'), (10, 'Special interest colleges')], null=True),
        ),
    ]
