# Generated by Django 5.0a1 on 2023-10-27 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_alter_department_department_start_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.collegeuser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_duration', models.PositiveIntegerField()),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_description', models.TextField()),
                ('languages', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('Chinese', 'Chinese')], max_length=10)),
                ('course_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('certificate_available', models.BooleanField(default=False)),
                ('exam', models.BooleanField(default=False)),
                ('assignment', models.BooleanField(default=False)),
                ('course_type', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.collegeuser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.department')),
                ('instructors', models.ManyToManyField(to='firstApp.instructor')),
            ],
        ),
    ]
