# Generated by Django 5.0a1 on 2023-10-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Programming', 'Programming'), ('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Cybersecurity', 'Cybersecurity'), ('Networking', 'Networking'), ('Database Management', 'Database Management'), ('Blockchain', 'Blockchain'), ('Cloud Computing', 'Cloud Computing'), ('Game Development', 'Game Development'), ('Graphic Design', 'Graphic Design'), ('User Experience (UX)', 'User Experience (UX)'), ('Project Management', 'Project Management'), ('Digital Marketing', 'Digital Marketing'), ('SEO Optimization', 'SEO Optimization'), ('Social Media Marketing', 'Social Media Marketing'), ('Content Creation', 'Content Creation'), ('Entrepreneurship', 'Entrepreneurship'), ('Business Analytics', 'Business Analytics'), ('Finance and Accounting', 'Finance and Accounting'), ('Human Resources', 'Human Resources'), ('Leadership and Management', 'Leadership and Management'), ('Public Speaking', 'Public Speaking'), ('Health and Wellness', 'Health and Wellness'), ('Nutrition and Dietetics', 'Nutrition and Dietetics'), ('Psychology', 'Psychology'), ('Language Learning', 'Language Learning'), ('Creative Writing', 'Creative Writing'), ('Music and Audio Production', 'Music and Audio Production'), ('Film and Video Production', 'Film and Video Production'), ('Photography', 'Photography'), ('Fine Arts', 'Fine Arts'), ('History and Culture', 'History and Culture'), ('Environmental Science', 'Environmental Science'), ('Sustainability', 'Sustainability'), ('Physics and Astronomy', 'Physics and Astronomy'), ('Chemistry', 'Chemistry'), ('Biology and Life Sciences', 'Biology and Life Sciences'), ('Mathematics', 'Mathematics'), ('Engineering', 'Engineering'), ('Robotics', 'Robotics'), ('Legal Studies', 'Legal Studies'), ('Educational Technology', 'Educational Technology'), ('Teaching and Training', 'Teaching and Training'), ('Sports and Fitness', 'Sports and Fitness'), ('Travel and Tourism', 'Travel and Tourism'), ('Real Estate', 'Real Estate'), ('E-commerce', 'E-commerce')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('practical', 'Practical'), ('image_question', 'Image Question'), ('fill_in_the_blanks', 'Fill in the Blanks'), ('matching_questions', 'Matching Questions')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('Chinese', 'Chinese'), ('Arabic', 'Arabic')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_assignments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='languages',
        ),
        migrations.AddField(
            model_name='course',
            name='course_tags',
            field=models.ManyToManyField(blank=True, to='firstApp.coursetag'),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_types',
            field=models.ManyToManyField(blank=True, to='firstApp.examtype'),
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(blank=True, to='firstApp.language'),
        ),
    ]
