# Generated by Django 5.0a1 on 2023-11-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0014_remove_multiplechoicequestion_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_profile_photos/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='subject_taught',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
