# Generated by Django 5.0a1 on 2023-11-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0016_alter_instructor_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
